[package]
name = "features"
edition = "2021"
version.workspace = true

[[bin]]
name = "sma"
path = "bin/sma.rs"

[[bin]]
name = "ema"
path = "bin/ema.rs"

[[bin]]
name = "rsi"
path = "bin/rsi.rs"

[dependencies]
technicalysis = { path = "../../../crates/core" }
