[package]
name = "technicalysis"
version = "0.1.0"
edition = "2021"
description = "Technical analysis library for financial market trading applications"
repository = "https://github.com/Guitheg/technicalysis.git"
license = "BSD-3-Clause"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }

[dev-dependencies]
