[build-system]
requires = ["maturin>=0.12"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "technicalysis._core"

[tool.pytest.ini_options]
testpaths = ["tests/python"]
